"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+3*jcw)p8vh8v75$2or6x-#)t9h*7^3kyj46p=lnv5dddlg1(n'




# SECURITY WARNING: don't run with debug turned on in production!

# Fichier: settings.py
########################################################################################
# --- GESTION DE L'ENVIRONNEMENT ---

# --- ÉTAPE 1 : CONFIGURATION POUR HTTPS ET HSTS ---

# Redirige toutes les requêtes non-HTTPS vers HTTPS.
# Ceci doit être utilisé lorsque votre serveur frontal (Nginx/Apache) gère déjà le SSL.
SECURE_SSL_REDIRECT = True

# Active HSTS (HTTP Strict Transport Security).
# 31536000 secondes = 1 an. Demande aux navigateurs de n'accéder au site qu'en HTTPS.
SECURE_HSTS_SECONDS = 31536000 

# Applique la politique HSTS à tous les sous-domaines.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Permet l'inscription de votre domaine dans la liste de préchargement HSTS du navigateur.
SECURE_HSTS_PRELOAD = True


# --- ÉTAPE 2 : ENFORCER LES COOKIES SÉCURISÉS (Nécessite HTTPS) ---

# Assure que le cookie de session n'est envoyé qu'avec une connexion HTTPS.
SESSION_COOKIE_SECURE = True

# Assure que le cookie CSRF n'est envoyé qu'avec une connexion HTTPS.
CSRF_COOKIE_SECURE = True




################################################################################
# --- Mesures de Sécurité Générales ---

# Étape 1: Désactiver le mode débogage en production
# CRITICAL: Doit être False en production.
DEBUG = False 

# Liste des hôtes autorisés en mode production.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.votredomaine.com'] 


# --- En-têtes de Sécurité ---

# X_FRAME_OPTIONS: Protection contre le Clickjacking.
# 'DENY' empêche l'affichage dans des iframes.
X_FRAME_OPTIONS = 'DENY' 

# SECURE_CONTENT_TYPE_NOSNIFF: Empêche le reniflage de type MIME.
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Ajoute l'en-tête X-XSS-Protection.
SECURE_BROWSER_XSS_FILTER = True 


# --- Sécurité des Cookies (Nécessite HTTPS) ---

# CSRF_COOKIE_SECURE: Assure que le cookie CSRF n'est envoyé qu'avec HTTPS.
CSRF_COOKIE_SECURE = True

# SESSION_COOKIE_SECURE: Assure que le cookie de session n'est envoyé qu'avec HTTPS.
SESSION_COOKIE_SECURE = True










# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    
]

# --- Configuration Obligatoire pour le Modèle Utilisateur Personnalisé ---
# Ceci doit être fait DÈS LE DÉBUT du projet.
AUTH_USER_MODEL = 'bookshelf.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CspMiddleware',################
]





########################################################################################
# --- Étape 4 : Configuration de la Politique de Sécurité du Contenu (CSP) ---

# NOTE: Ces paramètres sont utilisés par un middleware comme 'django-csp'.
# Assurez-vous d'ajouter ce middleware à la liste MIDDLEWARE si vous l'utilisez réellement.

# MIDDLEWARE = [
#     # ...
#     'csp.middleware.CspMiddleware',
#     # ...
# ]

# CSP_DEFAULT_SRC: Source par défaut. Seul le contenu de l'application elle-même est autorisé.
CSP_DEFAULT_SRC = ("'self'",)       

# CSP_SCRIPT_SRC: Sources autorisées pour les scripts (JS). 
# Bloque l'injection de scripts externes ou inline (XSS).
CSP_SCRIPT_SRC = ("'self'",) 

# CSP_STYLE_SRC: Sources autorisées pour les styles (CSS). 
# Autorise les styles inline (souvent nécessaires pour le développement/librairies).
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'",) 

# CSP_IMG_SRC: Sources autorisées pour les images. 
# Autorise les images de l'application, les données encodées (data:) et toute source externe (*).
CSP_IMG_SRC = ("'self'", "data:", "*")

# CSP_FONT_SRC: Sources autorisées pour les polices.
CSP_FONT_SRC = ("'self'",)





ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
